#!/bin/sh
# Builds and tests one of the two SDK variants (legacy: http/https, Node >=8; modern:
# fetch, Node >=18) from this single branch — no separate git branch or checkout
# involved. Stages the requested variant's package.json/package-lock.json/tsconfig.json
# (from node/variants/<variant>/) and transport.ts (from
# node/src/internal/transport.<variant>.ts) into their canonical top-level locations,
# then installs, builds, and runs the full test suite.
#
# The staged top-level files (package.json, package-lock.json, tsconfig.json,
# src/internal/transport.ts) are gitignored — they're always generated by this script,
# never the source of truth. That's why there's nothing to "restore": whichever variant
# ran last is simply what's sitting there until this script runs again.
#
# The two source files (src/internal/transport.legacy.ts / .modern.ts) live directly
# under src/internal/, at the same depth as the staged transport.ts target — not nested
# a level deeper — specifically so their relative imports (e.g. '../constants') resolve
# identically whether read from their own filename or after being copied to
# transport.ts.
#
# Usage:
#   node/scripts/build-variant.sh legacy
#   node/scripts/build-variant.sh modern
#
# This script is one of the files that must stay identical regardless of which variant
# is currently staged — it lives outside variants/ for exactly that reason.
set -eu

VARIANT="${1:-}"
case "$VARIANT" in
  legacy|modern) ;;
  *)
    echo "Usage: $0 <legacy|modern>" >&2
    exit 2
    ;;
esac

cd "$(git rev-parse --show-toplevel)/node"

cp "variants/${VARIANT}/package.json" package.json
cp "variants/${VARIANT}/package-lock.json" package-lock.json
cp "variants/${VARIANT}/tsconfig.json" tsconfig.json
cp "src/internal/transport.${VARIANT}.ts" src/internal/transport.ts

npm install --silent
npm run build --silent

node test/smoke.js
node test/model/incidentRequest.test.js
node test/internal/wireCodec.test.js
node test/internal/retryExecutor.test.js
node test/internal/asyncDispatcher.test.js
node test/internal/transport.test.js
node test/IncidentClient.test.js

echo "Built and tested the $VARIANT variant successfully."
